version: '3.8'
services:
  api:
    container_name: api
    build: .
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: .
        target: /api
  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: legends
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/my.cnf
      - mysql:/var/lib/mysql
volumes:
  mysql:
